### ISSUE TITLE
empty processed .txt files when running preprocess_dbrd.py

### ISSUE THREAD

**Issue by tvdermeer** [iPieter/RobBERT#11]
Hi there,

First of all thanks for your research and repository. I was trying to replicate your book review lm fine tuning but when running preprocess_dbrd.py i come up with empty .txt files in the processed folder. I don't get any errors while running the file so i can't show you any output or error logs. 

Anyway, if you could take a look if the error also happens to exist with you, thanks in advance,

Thomas

**Comment by twinters** [comment]
Hi!
Thanks for the headsup! There were some pull requests related to this preprocessing file.
It might be that one of those broke the script for your system.
We'll look into it!

For now, you could maybe check if rolling back to an earlier commit (before the recent changes to this file) fixes this for you.

Hope this helps!
