### ISSUE TITLE
transformers and other library versions missing from requirements.txt

### ISSUE THREAD

**Issue by ogencoglu** [iPieter/RobBERT#18]
Hi,

`requirements.txt` seem to be missing several library version like _transformers, tqdm, pandas,_ etc. to replicate the experiments.

**Comment by twinters** [comment]
Hi Oguzhan!

Thanks for notifying us! I've added missing requirements to the requirements.txt
The reason they were missing is because most of the experiments were run using Pipfile instead of requirements.txt, so thanks for informing us!
