### ISSUE TITLE
Can't find finetune_dbrd.ipynb

### ISSUE THREAD

**Issue by stefanknegt** [iPieter/RobBERT#2]
First of all, thanks for sharing your code!

In the readme you mention the following: 

> Sentiment analysis using the Dutch Book Review Dataset

> Download the Dutch book review dataset from https://github.com/benjaminvdb/110kDBRD, and save it to data/raw/110kDBRD
> Run src/preprocess_dbrd.py to prepare the dataset.
> Follow the notebook notebooks/finetune_dbrd.ipynb to finetune the model.

However, I cannot find this file. Could you upload it? Thanks!

**Comment by iPieter** [comment]
Thank you for highlighting this issue! We've added the file [here](https://github.com/iPieter/RobBERT/blob/master/notebooks/finetune_dbrd.ipynb). Hopefully this is useful.
