### ISSUE TITLE
Maximum sequence length tokenizer

### ISSUE THREAD

**Issue by danieldk** [iPieter/RobBERT#28]
It would be nice if `model_max_length` could be set in the tokenizer configuration. If this is not set, the maximum length as input to the transformer model will be set to `VERY_LARGE_INTEGER` (1e30):

https://huggingface.co/transformers/main_classes/tokenizer.html#pretrainedtokenizer

This then leads to an exception in the embedding lookup, because the model will attempt to index the position embedings with positions >= 512.

**Comment by iPieter** [comment]
We fixed this in [#e28720](https://huggingface.co/pdelobelle/robbert-v2-dutch-base/commit/e28720e1a6cdf68ed3418c67a1964392905a7c8a). Sorry for the delay.
