### ISSUE TITLE
Using the model in tensorflow

### ISSUE THREAD

**Issue by melvinvandenbout** [iPieter/RobBERT#3]
Would it be possible to use this model in tensorflow? I think i need the pre-trained model in a format like (bert_model.ckpt, vocab.txt, bert_config.json), just like https://github.com/google-research/bert#pre-trained-models.

**Comment by twinters** [comment]
I personally don't see an easy way of achieving this. I heard there are ways of translating PyTorch models to Tensorflow models using [ONNX](https://onnx.ai/supported-tools.html), but RobBERT is probably too complex for that.
You might want to search if someone ever succeeded in translating [RoBERTa](https://github.com/pytorch/fairseq/tree/master/examples/roberta) to Tensorflow: if you have such an algorithm, it would trivially work for our RobBERT model as well.

I think these kind of incompatibilities is probably why a lot of people (including Pieter and me) shift towards using [HuggingFace transformers](https://github.com/huggingface/transformers), as they provide a nice overarching framework for these kind of models. Might we worthwhile changing your set-up to their framework if you want to use multiple different types of transformers.

**Comment by melvinvandenbout** [comment]
Thanks for your elaboration & insightful comment!
